baseURL = "https://entropy-warrior.github.io/"
languageCode = "en-us"
title = "Perspective Tensor"
theme = "PaperMod"
paginate = 10

[params]
  author = "Lin Wang"
  description = "Documenting my evolving perspectives on a lifelong journey of learning."
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = true
  disableHLJS = true
  comments = false

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/About/"
    weight = 4
  [[menu.main]]
    name = ''
    url = 'https://www.linkedin.com/in/linwang4ds/'
    weight = 5
    post = '<i class="fab fa-linkedin"></i>'  